
export const languages = [
  { value: 'en-US', label: 'English (US)' },
  { value: 'es-ES', label: 'Español' },
  { value: 'fr-FR', label: 'Français' },
  { value: 'de-DE', label: 'Deutsch' },
  { value: 'it-IT', label: 'Italiano' },
  { value: 'ja-JP', label: '日本語' },
  { value: 'hi-IN', label: 'हिन्दी' },
  { value: 'ta-IN', label: 'தமிழ்' },
];

export const uiContent = {
  'en-US': {
    appName: 'PillPal Reminder',
    addMedication: 'Add New Medication',
    medicationName: 'Medication Name',
    dosage: 'Dosage',
    time: 'Time',
    language: 'Language',
    saveMedication: 'Save Medication',
    noMedications: 'Your schedule is clear!',
    alarmTitle: 'Time for your medication!',
    snooze: 'Snooze (5 min)',
    dismiss: "I've taken it",
    yourSchedule: "Your Schedule",
    customReminder: "Custom Reminder Message (Optional)",
    customReminderPlaceholder: "e.g., 'Take with food.' or leave blank for default.",
    medicationImage: "Medication Image",
    uploadImage: "Click to upload image",
    dashboard: "Dashboard",
    suggestions: "Suggestions",
    monitorIntake: "Monitor Your Intake",
    appointments: "Doctor's Appointments",
    addAppointment: "Add Appointment",
    date: "Date",
    doctorName: "Doctor's Name",
    notes: "Notes",
    symptomChecker: "Symptom Checker",
    describeSymptoms: "Describe your symptoms...",
    getSuggestion: "Get Suggestion",
    suggestionResult: "Suggestion Result",
    disclaimer: "Disclaimer: This is not medical advice. Consult a healthcare professional.",
    profile: "Profile",
  },
  'es-ES': {
    appName: 'PillPal Recordatorio',
    addMedication: 'Añadir Nuevo Medicamento',
    medicationName: 'Nombre del Medicamento',
    dosage: 'Dosis',
    time: 'Hora',
    language: 'Idioma',
    saveMedication: 'Guardar Medicamento',
    noMedications: '¡Tu horario está libre!',
    alarmTitle: '¡Hora de tu medicamento!',
    snooze: 'Posponer (5 min)',
    dismiss: 'Ya lo he tomado',
    yourSchedule: "Tu Horario",
    customReminder: "Mensaje de Recordatorio Personalizado (Opcional)",
    customReminderPlaceholder: "p.ej., 'Tomar con comida.' o dejar en blanco para el predeterminado.",
    medicationImage: "Imagen del Medicamento",
    uploadImage: "Haga clic para subir la imagen",
    dashboard: "Tablero",
    suggestions: "Sugerencias",
    monitorIntake: "Monitorea tu ingesta",
    appointments: "Citas Médicas",
    addAppointment: "Añadir Cita",
    date: "Fecha",
    doctorName: "Nombre del Doctor",
    notes: "Notas",
    symptomChecker: "Verificador de Síntomas",
    describeSymptoms: "Describe tus síntomas...",
    getSuggestion: "Obtener Sugerencia",
    suggestionResult: "Resultado de la Sugerencia",
    disclaimer: "Descargo de responsabilidad: Esto no es un consejo médico. Consulte a un profesional de la salud.",
    profile: "Perfil",
  },
  'fr-FR': {
    appName: 'PillPal Rappel',
    addMedication: 'Ajouter un nouveau médicament',
    medicationName: 'Nom du médicament',
    dosage: 'Dosage',
    time: 'Heure',
    language: 'Langue',
    saveMedication: 'Enregistrer',
    noMedications: 'Votre programme est vide !',
    alarmTitle: 'C\'est l\'heure de votre médicament !',
    snooze: 'Répéter (5 min)',
    dismiss: 'Je l\'ai pris',
    yourSchedule: "Votre Programme",
    customReminder: "Message de Rappel Personnalisé (Optionnel)",
    customReminderPlaceholder: "p.ex., 'Prendre avec de la nourriture.' ou laisser vide pour le défaut.",
    medicationImage: "Image du Médicament",
    uploadImage: "Cliquez pour télécharger l'image",
    dashboard: "Tableau de Bord",
    suggestions: "Suggestions",
    monitorIntake: "Surveillez votre consommation",
    appointments: "Rendez-vous médicaux",
    addAppointment: "Ajouter un rendez-vous",
    date: "Date",
    doctorName: "Nom du médecin",
    notes: "Remarques",
    symptomChecker: "Vérificateur de symptômes",
    describeSymptoms: "Décrivez vos symptômes...",
    getSuggestion: "Obtenir une suggestion",
    suggestionResult: "Résultat de la suggestion",
    disclaimer: "Avis de non-responsabilité : Il ne s'agit pas d'un avis médical. Consultez un professionnel de la santé.",
    profile: "Profil",
  },
  'de-DE': {
    appName: 'PillPal Erinnerung',
    addMedication: 'Neues Medikament hinzufügen',
    medicationName: 'Medikamentenname',
    dosage: 'Dosis',
    time: 'Uhrzeit',
    language: 'Sprache',
    saveMedication: 'Speichern',
    noMedications: 'Ihr Zeitplan ist leer!',
    alarmTitle: 'Zeit für Ihre Medikamente!',
    snooze: 'Schlummern (5 Min.)',
    dismiss: 'Ich habe es genommen',
    yourSchedule: "Ihr Zeitplan",
    customReminder: "Benutzerdefinierte Erinnerungsnachricht (Optional)",
    customReminderPlaceholder: "z.B., 'Mit dem Essen einnehmen.' oder für Standard leer lassen.",
    medicationImage: "Medikamentenbild",
    uploadImage: "Klicken Sie hier, um das Bild hochzuladen",
    dashboard: "Dashboard",
    suggestions: "Vorschläge",
    monitorIntake: "Überwachen Sie Ihre Einnahme",
    appointments: "Arzttermine",
    addAppointment: "Termin hinzufügen",
    date: "Datum",
    doctorName: "Name des Arztes",
    notes: "Notizen",
    symptomChecker: "Symptomprüfer",
    describeSymptoms: "Beschreiben Sie Ihre Symptome...",
    getSuggestion: "Vorschlag erhalten",
    suggestionResult: "Vorschlagsergebnis",
    disclaimer: "Haftungsausschluss: Dies ist keine medizinische Beratung. Konsultieren Sie einen Arzt.",
    profile: "Profil",
  },
  'it-IT': {
    appName: 'PillPal Promemoria',
    addMedication: 'Aggiungi farmaco',
    medicationName: 'Nome del farmaco',
    dosage: 'Dosaggio',
    time: 'Orario',
    language: 'Lingua',
    saveMedication: 'Salva farmaco',
    noMedications: 'Il tuo programma è vuoto!',
    alarmTitle: 'È ora di prendere la medicina!',
    snooze: 'Posticipa (5 min)',
    dismiss: 'L\'ho preso',
    yourSchedule: "Il tuo programma",
    customReminder: "Messaggio di Promemoria Personalizzato (Opzionale)",
    customReminderPlaceholder: "es., 'Assumere con il cibo.' o lasciare vuoto per l'impostazione predefinita.",
    medicationImage: "Immagine del Farmaco",
    uploadImage: "Clicca per caricare l'immagine",
    dashboard: "Cruscotto",
    suggestions: "Suggerimenti",
    monitorIntake: "Monitora la tua assunzione",
    appointments: "Appuntamenti dal medico",
    addAppointment: "Aggiungi appuntamento",
    date: "Data",
    doctorName: "Nome del medico",
    notes: "Note",
    symptomChecker: "Controllo dei sintomi",
    describeSymptoms: "Descrivi i tuoi sintomi...",
    getSuggestion: "Ottieni suggerimento",
    suggestionResult: "Risultato del suggerimento",
    disclaimer: "Dichiarazione di non responsabilità: questo non è un consiglio medico. Consultare un operatore sanitario.",
    profile: "Profilo",
  },
  'ja-JP': {
    appName: 'ピルパルリマインダー',
    addMedication: '新しい薬を追加',
    medicationName: '薬の名前',
    dosage: '服用量',
    time: '時間',
    language: '言語',
    saveMedication: '保存',
    noMedications: 'スケジュールは空です！',
    alarmTitle: 'お薬の時間です！',
    snooze: 'スヌーズ（5分）',
    dismiss: '服用しました',
    yourSchedule: "あなたのスケジュール",
    customReminder: "カスタムリマインダーメッセージ（任意）",
    customReminderPlaceholder: "例：「食事と一緒に服用してください」デフォルトの場合は空白のままにします。",
    medicationImage: "薬の画像",
    uploadImage: "クリックして画像をアップロード",
    dashboard: "ダッシュボード",
    suggestions: "提案",
    monitorIntake: "摂取量を監視する",
    appointments: "医師の診察予約",
    addAppointment: "予約を追加",
    date: "日付",
    doctorName: "医師名",
    notes: "メモ",
    symptomChecker: "症状チェッカー",
    describeSymptoms: "症状を説明してください...",
    getSuggestion: "提案を得る",
    suggestionResult: "提案結果",
    disclaimer: "免責事項：これは医療アドバイスではありません。医療専門家にご相談ください。",
    profile: "プロフィール",
  },
  'hi-IN': {
    appName: 'पिलपाल रिमाइंडर',
    addMedication: 'नई दवा जोड़ें',
    medicationName: 'दवा का नाम',
    dosage: 'खुराक',
    time: 'समय',
    language: 'भाषा',
    saveMedication: 'सहेजें',
    noMedications: 'आपका शेड्यूल खाली है!',
    alarmTitle: 'आपकी दवा का समय हो गया है!',
    snooze: 'स्नूज़ (5 मिनट)',
    dismiss: 'मैंने ले ली है',
    yourSchedule: "आपका शेड्यूल",
    customReminder: "कस्टम रिमाइंडर संदेश (वैकल्पिक)",
    customReminderPlaceholder: "जैसे, 'भोजन के साथ लें' या डिफ़ॉल्ट के लिए खाली छोड़ दें।",
    medicationImage: "दवा की छवि",
    uploadImage: "छवि अपलोड करने के लिए क्लिक करें",
    dashboard: "डैशबोर्ड",
    suggestions: "सुझाव",
    monitorIntake: "अपने सेवन की निगरानी करें",
    appointments: "डॉक्टर से मिलने का समय",
    addAppointment: "अपॉइंटमेंट जोड़ें",
    date: "तारीख",
    doctorName: "डॉक्टर का नाम",
    notes: "टिप्पणियाँ",
    symptomChecker: "लक्षण परीक्षक",
    describeSymptoms: "अपने लक्षणों का वर्णन करें...",
    getSuggestion: "सुझाव प्राप्त करें",
    suggestionResult: "सुझाव परिणाम",
    disclaimer: "अस्वीकरण: यह चिकित्सा सलाह नहीं है। किसी स्वास्थ्य देखभाल पेशेवर से परामर्श लें।",
    profile: "प्रोफ़ाइल",
  },
  'ta-IN': {
    appName: 'பில்பால் நினைவூட்டி',
    addMedication: 'புதிய மருந்து சேர்க்கவும்',
    medicationName: 'மருந்தின் பெயர்',
    dosage: 'மருந்தளவு',
    time: 'நேரம்',
    language: 'மொழி',
    saveMedication: 'சேமி',
    noMedications: 'உங்கள் அட்டவணை காலியாக உள்ளது!',
    alarmTitle: 'உங்கள் மருந்துக்கான நேரம்!',
    snooze: 'தள்ளிப்போடு (5 நிமிடம்)',
    dismiss: 'நான் எடுத்துக்கொண்டேன்',
    yourSchedule: "உங்கள் அட்டவணை",
    customReminder: "தனிப்பயன் நினைவூட்டல் செய்தி (விருப்பத்தேர்வு)",
    customReminderPlaceholder: "எ.கா., 'உணவுடன் எடுத்துக் கொள்ளுங்கள்.' அல்லது இயல்புநிலைக்கு காலியாக விடவும்.",
    medicationImage: "மருந்து படம்",
    uploadImage: "படத்தை பதிவேற்ற கிளிக் செய்யவும்",
    dashboard: "டாஷ்போர்டு",
    suggestions: "பரிந்துரைகள்",
    monitorIntake: "உங்கள் உட்கொள்ளலைக் கண்காணிக்கவும்",
    appointments: "மருத்துவர் சந்திப்புகள்",
    addAppointment: "சந்திப்பைச் சேர்க்கவும்",
    date: "தேதி",
    doctorName: "மருத்துவர் பெயர்",
    notes: "குறிப்புகள்",
    symptomChecker: "அறிகுறி சரிபார்ப்பு",
    describeSymptoms: "உங்கள் அறிகுறிகளை விவரிக்கவும்...",
    getSuggestion: "பரிந்துரையைப் பெறுங்கள்",
    suggestionResult: "பரிந்துரை முடிவு",
    disclaimer: "பொறுப்புத் துறப்பு: இது மருத்துவ ஆலோசனை அல்ல. ஒரு சுகாதார நிபுணரை அணுகவும்.",
    profile: "சுயவிவரம்",
  },
};

export type LanguageKey = keyof typeof uiContent;

export const getUIContent = (lang: LanguageKey) => uiContent[lang] || uiContent['en-US'];

    